version: "3.3"

services:
    db:
        image: harbor.tallerdevops.com/grupo-2/mongo:5.0.3-focal
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
            - MONGO_INITDB_DATABASE=course-goals 
        networks:
            - tp-project
        restart: always
        volumes:
            - type: bind
              source: ./database-data
              target: /data/db
            - type: bind
              source: ./mongo-init.js
              target: /docker-entrypoint-initdb.d/mongo-init.js
    back-end:
        container_name: be
        build:
            context: ./BE/
            dockerfile: Dockerfile
        environment:
            - MONGO_HOST=root:secret@mongodb
            - MONGO_DB=course-goals
        networks:
            - tp-project
        restart: always
        depends_on:
            - db
    front-end:
        container_name: fe
        build:
            context: ./FE/
            dockerfile: Dockerfile
        networks:
            - tp-project
        restart: always
        ports:
            - "8081:80"
        depends_on:
            - db
            - back-end
networks:
    tp-project:
        driver: bridge
